language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=https://github.com/django/django/zipball/master
  - DJANGO=django==1.5 --use-mirrors
  - DJANGO=django==1.4.5 --use-mirrors
  - DJANGO=django==1.3.7 --use-mirrors

install:
  - pip install $DJANGO
  - pip install pytz==2013b --use-mirrors
  - pip install south==0.7.6 --use-mirrors
  - pip install oauthlib==0.3.8 --use-mirrors

script:
  - python runtests.py
